apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-in-container-service
  name: spring-in-container-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-in-container-service
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-in-container-service
    spec:
      containers:
        - image: gcr.io/ut-265822/spring-in-container:v1
          name: spring-in-container-service
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /time
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /time
              port: 8080
            initialDelaySeconds: 10
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-in-container-service
  labels:
    name: spring-in-container-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-in-container-service
  type: LoadBalancer
