apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "mysql:5.7"
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: secret-config
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secret-config
                  key: mysql_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secret-config
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: secret-config
                  key: mysql_database
          ports:
            - containerPort: 3306
              name: mysql
