apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: "mysql:5.7"
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: secret-config
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: secret-config
              key: mysql_password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: secret-config
              key: mysql_root_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: secret-config
              key: mysql_database
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
       - name: mysql-storage
         mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage
      gcePersistentDisk:
        fsType: ext4
        pdName: mysql-disk