apiVersion: skaffold/v1
kind: Config
metadata:
  name: my-skaffold-spring-in-container
build:
  local:
    push: false
  # Generated artifact
  artifacts:
    - image: gcr.io/ut-265822/spring-in-container
      # Use jibMaven
      jib: {}
deploy:
  kubectl:
    manifests:
      - ./k8s/*.yaml