apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-container
  name: spring-container
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: spring-container
status:
  loadBalancer: {}